### ISSUE TITLE
DMtimer seems to block after some time - Long overflow ?

### ISSUE THREAD

**Issue by Koraze** [toxnico/DMTimer#1]
Hi, sorry for my bad english.

I build an ESP8266 (NodeMCU) robot and it seems your lib blocks the robot after some hours. I think it is because of long overflow inside your code. After some time the "currentTimer" turns back to 0 making this condition `"if(currentTime > _lastTime + interval)"` not working anymore. So I suggest you to make this small fix :

Remplace `if(currentTime > _lastTime + interval)`
by `if(currentTime - _lastTime > interval)`

Because it's my first time on github. I don't really know how to propose this fix in another way.
I'm testing this new fix right now. If I don't go back, it's because it seems to work ;)

Thanks for your lib

**Comment by toxnico** [comment]
Hi @Koraze,
First : SORRY for the delay.
You are right, I just corrected the test according to your hint to ensure it works even after overflow  :)

Cheers
